version: "3"

services:
  login-page:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    volumes:
      - ./challenge/:/app
    ports:
      - 1211:80/tcp
    environment:
      - FLAG=Alphabit{4no7heR_1NJ3C71On_D1d_u_pl4Y_i51cTf}
      - PASSWORD=supersecretpasswordandimpossibletocrack