version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2500:1337
    environment:
      - FLAG=Alphabit{N0_bl4ckl157_15_fl4wl355_wh3n_3mpl0y1ng_th3_un1d3c0d3}
    restart: always
