version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2500:1337
    environment:
      - FLAG=Alphabit{pr073c7_y0ur_s3lf_fr0m_SQL_injection}
    restart: always
