version: "3"

services:
  server:
    build: .
    ports:
      - 1004:1004
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M
    healthcheck:
      test: socat - TCP4:localhost:1004 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
